### ISSUE TITLE
DynaForm: readOnly attribute

### ISSUE THREAD

**Issue by pzoli** [primefaces-extensions/primefaces-extensions.github.com#698] opened 2019-05-09 13:37 UTC
I set readOnly attribute by program in a dynaForm, but not works for me. Is this a correct way?

		if (rights.readOnly() != null) {
			Boolean readonly = evalELToBoolean(rights.readOnly());
			if (readonly != null && readonly) {
				component.getAttributes().put("readOnly",true);
			}
		}

**Comment by melloware** [comment] 2019-05-10 01:20
@Rapster is the DynaForm expert I will wait for him to chime in.

**Comment by pzoli** [comment] 2019-05-11 15:32
I use version 7.0

**Comment by Rapster** [comment] 2019-05-12 10:28
Hi,

Sorry I'm kinda taking a break from PF issues lately... But by the sound of it, it looks like a duplicate of #571. As far as I can remember, I thought I fixed it, but @melloware had issues after this fix. So, whenever I'll have time to investigate on this, I'll let you know

**Comment by melloware** [comment] 2019-05-23 12:12
Marking as duplicate for now as its tracked in the other issue.

**Closed by melloware** 2019-05-23 12:12 UTC
Labels: duplicate
