### ISSUE TITLE
Sheet: click in a cell triggers scrolling to top (Firefox only)

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions.github.com#611] opened 2018-09-06 10:31 UTC
whenever I click in a cell my page scrolls to the top.

Reproduce: https://web2.fa.knaw.nl/oat/ (ask me for login and steps via mail or message)

**Comment by melloware** [comment] 2018-09-06 11:52
Can you reproduce using our showcase or better yet a simple [Primefaces Test](https://github.com/primefaces/primefaces-test) project so I can debug it myself?

**Comment by eduarddrenth** [comment] 2018-09-06 13:05
I'll see what I can do...our data is in a db, so it will take some tweaking....

**Comment by melloware** [comment] 2018-09-06 14:54
You might be able to just fake the data in the Controller like we do in the ShowCase and just generate 100 rows or 1000 rows of fake data that is similar to your data.

**Comment by eduarddrenth** [comment] 2018-09-06 21:30
That sure sounds like my problem

**Comment by melloware** [comment] 2018-09-07 11:30
Can you check somewhere in your styling if you see "overflow-y: scroll;" in maybe the panel that houses the sheet?

**Comment by eduarddrenth** [comment] 2018-09-07 13:59
In my own styling no and I've searched for it in all the styling, no overflow-y I believe

**Comment by eduarddrenth** [comment] 2018-09-07 14:05
Checked ff dev tool, computed style: body has overflow-y: hidden, ui-panel-content has overflow-y:auto

**Comment by eduarddrenth** [comment] 2018-09-08 06:58
html also has overflow-y: hidden.

if I remove all overflow styling the behaviour remains the same

**Comment by melloware** [comment] 2018-09-08 12:26
Hmm OK if you can reproduce it using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project might be the only way I can see what is going on.  That way I can figure out if its a HandsonTable bug.

**Comment by melloware** [comment] 2018-09-09 12:36
OK I tested it out today.  I followed your exact instructions and the Sheet seems to be behaving OK for me.  When I click in cells it stays focused as normal.   Everything in your app appears to be working normally for me?

I am using Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Have you tried pressing CTRL+F5 to force a reload of all JS and CSS?

**Comment by melloware** [comment] 2018-09-09 14:36
Ahh Firefox is a detail you left out.  OK it's most likely a Firefox issue, what version are you running of Firefox?

**Comment by melloware** [comment] 2018-09-09 14:39
Lokos like it is Firefox specific: https://github.com/handsontable/handsontable/issues/5242

**Comment by eduarddrenth** [comment] 2018-09-09 15:38
ubuntu 1804 ff 62.0

**Comment by lucasncne** [comment] 2018-09-10 19:05
Maybe this can help you: [https://github.com/handsontable/handsontable/issues/7](url)

**Comment by melloware** [comment] 2018-09-10 19:45
That does look promising!

**Comment by eduarddrenth** [comment] 2018-09-11 05:04
Yes, that solves the jumping issue,  It doesn't solve #612 though.

**Comment by melloware** [comment] 2018-09-11 11:42
Looks like there is a permanent fix for this scroll to top coming in the next release: https://github.com/handsontable/handsontable/issues/5220

**Comment by AMBudnik** [comment] 2018-09-12 11:36
Closed with https://github.com/handsontable/handsontable/issues/5220

**Comment by melloware** [comment] 2018-09-12 11:41
I updated to Handsontable 5.0.2 today which resolves this issue.

**Closed by melloware** 2018-09-12 11:41 UTC
Labels: bug
