### ISSUE TITLE
Timeline problem with primefaces.CLIENT_SIDE_VALIDATION set to true

### ISSUE THREAD

**Issue by raelianer** [primefaces-extensions/primefaces-extensions.github.com#307] opened 2015-02-11 13:48 UTC
Just wanted to note that

    <context-param>
        <param-name>primefaces.CLIENT_SIDE_VALIDATION</param-name>
        <param-value>true</param-value>
    </context-param>

leads to this error when trying to open the website of the showcase:

    Error Rendering View[/sections/timeline/editServer.xhtml]
    javax.el.PropertyNotFoundException: /sections/timeline/detailsDialog.xhtml @14,56 value="#{editServerTimelineController.event.data.roomNumber}": Target unreachable, base expression '. data' resolved to null

(primefaces extensions 3.0.0 - showcase revision b9054309cc)

Update:
my bad - setting to true not to false leads to the error

full stack traces:

    Schwerwiegend:   Error Rendering View[/sections/timeline/editServer.xhtml]
    javax.el.PropertyNotFoundException: /sections/timeline/detailsDialog.xhtml @14,56 value="#{editServerTimelineController.event.data.roomNumber}": Target unreachable, base expression '. data' resolved to null
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:100)
	at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:128)
	at org.primefaces.renderkit.CoreRenderer.renderValidationMetadata(CoreRenderer.java:557)
	at org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(InputTextRenderer.java:86)
	at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:52)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312)
	at com.sun.faces.renderkit.html_basic.GridRenderer.renderRow(GridRenderer.java:185)
	at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:129)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:115)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:79)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:66)
	at org.primefaces.component.dialog.DialogRenderer.encodeContent(DialogRenderer.java:180)
	at org.primefaces.component.dialog.DialogRenderer.encodeMarkup(DialogRenderer.java:109)
	at org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:47)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.primefaces.extensions.showcase.webapp.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.el.PropertyNotFoundException: Target unreachable, base expression '. data' resolved to null
	at de.odysseus.el.tree.impl.ast.AstProperty.getType(AstProperty.java:102)
	at de.odysseus.el.tree.impl.ast.AstEval.getType(AstEval.java:75)
	at de.odysseus.el.TreeValueExpression.getType(TreeValueExpression.java:110)
	at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:98)
	... 64 more

    Warnung:   StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
    javax.el.PropertyNotFoundException: Target unreachable, base expression '. data' resolved to null
	at de.odysseus.el.tree.impl.ast.AstProperty.getType(AstProperty.java:102)
	at de.odysseus.el.tree.impl.ast.AstEval.getType(AstEval.java:75)
	at de.odysseus.el.TreeValueExpression.getType(TreeValueExpression.java:110)
	at org.jboss.weld.el.WeldValueExpression.getType(WeldValueExpression.java:93)
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:98)
	at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:128)
	at org.primefaces.renderkit.CoreRenderer.renderValidationMetadata(CoreRenderer.java:557)
	at org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(InputTextRenderer.java:86)
	at org.primefaces.component.inputtext.InputTextRenderer.encodeEnd(InputTextRenderer.java:52)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312)
	at com.sun.faces.renderkit.html_basic.GridRenderer.renderRow(GridRenderer.java:185)
	at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:129)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:115)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:79)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:66)
	at org.primefaces.component.dialog.DialogRenderer.encodeContent(DialogRenderer.java:180)
	at org.primefaces.component.dialog.DialogRenderer.encodeMarkup(DialogRenderer.java:109)
	at org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:47)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.primefaces.extensions.showcase.webapp.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tandraschko** [comment] 2015-02-11 13:59
Oleg, WDYT?
I would close it, our showcase is designed with the configs in our web.xml. I would not change it to work in cases when the user changes our web.xml.

**Comment by ova2** [comment] 2015-02-11 16:13
I can not imagine that client side validation leads to ```PropertyNotFoundException```. By the way, AFAIK, ```primefaces.CLIENT_SIDE_VALIDATION``` is not set in our showcase too .

Please check your log file. It probably have other exceptions. Thomas, I would close this issue too.

**Comment by raelianer** [comment] 2015-02-11 22:21
The showcase runs until I change the setting, so I think it has something to do with this issue. As I wanted to use the primefaces extensions with spring security and other things, I had to find out if it works. Therefore I used the showcase examples.
I just wanted to let you know about this behaviour. Maybe you wanna add a line to the showcase to tell users that they should not change the setting. I don't even know if it's a showcase problem or a problem of the component. I'm not expecting anything, just thought maybe you wanted to know about this.

**Comment by ova2** [comment] 2015-02-12 07:59
I can look into this later if I have time. Thanks for reporting.

**Comment by ova2** [comment] 2015-02-13 12:05
Will check this before we release the next version 3.1.0. Timeline should work of course, independent from primefaces.CLIENT_SIDE_VALIDATION setting.

**Comment by ova2** [comment] 2015-03-18 22:13
Hmm.. That's true. It is due to p:inputText. It works with non PF components, e.g. h:inputText.

I have to look deeper into this. Thomas, do you have an idea?

**Comment by tandraschko** [comment] 2015-03-18 22:47
sure. CSV needs to resolve the annotations on the referenced VALUE_EXPRESSION, if a variable resolves to null in the whole expression, it's not readable.
Currently thats by design in PF - a solution would be to catch the NPE but CSV wouldn't work for this field as we can't extract the constraints... So, whats better? ;)

**Comment by ova2** [comment] 2015-03-18 23:02
Understood. Would it solve the problem if we use rendered on the input field to check if some objects are null?

**Comment by ova2** [comment] 2015-03-18 23:04
Also checking constraints is only important for BV. So PF could catch NPE if no BV is used.

**Comment by tandraschko** [comment] 2015-03-19 07:04
Thats how it's done.
But the stacktrace is from a different point. It's done for BV and !=BV to lookup the converter.

**Comment by ova2** [comment] 2015-03-19 20:16
I added to all input components in detailsDialog.xhtml

rendered="#{not empty editServerTimelineController.event}"

and the problem was gone. You can do the same in the future with primefaces.CLIENT_SIDE_VALIDATION = true.

**Closed by ova2** 2015-03-19 20:16 UTC
Labels: bug
