### ISSUE TITLE
TimePicker treat EET as EEST

### ISSUE THREAD

**Issue by chabapok** [primefaces-extensions/primefaces-extensions.github.com#521] opened 2018-01-11 20:59 UTC
Let's try next code:

```
@ManagedBean(name = "myBean")
public class MyBean {

    Date t = new Date(0);

    public String getOffset(){
        return Calendar.getInstance().getTimeZone().getDisplayName()+ "/"+
                Calendar.getInstance().getTimeZone().getRawOffset();
    }

    public Date getT() {
        return t;
    }

    public void setT(Date t) {
        this.t = t;
    }
}
```

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:p="http://primefaces.org/ui"
        xmlns:pe="http://primefaces.org/ui/extensions">

<h:body>
<pe:timePicker value="#{myBean.t}" mode="popup" />
<p:outputLabel value="#{myBean.offset}" />
</h:body>
</html>
```

Result: `03:00    Eastern European Time/7200000`

But must be 02:00 in winter (EET) and 03:00 in summer(EEST)

**Comment by melloware** [comment] 2018-01-11 22:48
You need to set the timezone of the picker by using an f converter to tell it the timezone of the picker.  What timezone you choose is up to you...

```xml
<pe:timePicker id="calStartTime" value="#{startTime}">
	<f:convertDateTime type="time" pattern="HH:mm" timeZone="EET" />
</pe:timePicker>
```

**Comment by chabapok** [comment] 2018-01-12 06:04
This solution works fine only in winter (without daylight saving time).
How to setup to use Daylight Saving Time in summer, but not use it in winter?
I tested this:
```
timeZone="Europe/Kiev"
```
but it not works.

As far as I understand, there is a tricky way: `timeZone="#{myBean.currentTimezone}"` and bind this property to GMT+2 or GMT+3 (depending on the current DST). Is there a more simply way?

**Comment by melloware** [comment] 2018-01-12 12:14
1. The simplest way is use a Timezone that supports DST.  For example I use "America/New_York" and it switched between GMT+4 and GMT+5 as DST transitions automatically.  If I however used "EST" and "EDT" I would have transition them manually like you discussed. 

So do you have a proper timezone that respected the DST transition you have?  If not you will have to do exactly what you said and use `timeZone="#{myBean.currentTimezone}"`

 I am closing this ticket as the TimePicker is doing what it is supposed to do and properly working with Timezones.

**Closed by melloware** 2018-01-12 12:14 UTC
Labels: invalid

**Comment by chabapok** [comment] 2018-01-12 15:31
Row "Daylight Saving Time: No" in the you link treated as "not activated now". For example, at https://timezonedb.com/time-zones/America/New_York Row DST not activated now too. "Europe/Kiev" support DST.

If I use "America/New_York" timezome, and test with clock 01/12/2018 and 07/07/2018. Both tests show equals result:
```
19:00 Eastern Standard Time/-18000000
```

As far, as I understand, it's incorrect. At 07/07/2018 should be 20:00 (GMT-4)

**Comment by melloware** [comment] 2018-01-12 15:35
OK.  What timezone is your JVM running as?  Hopefully "Europe/Kiev" right?

**Comment by melloware** [comment] 2018-01-12 15:37
Oh I think the issue is the timePicker always uses Jan 1, 1970 as its date.   So the hour is considered from that.  It doesn't actually know the current date to do the TZ conversion.

When you do this print out the full date and not just the time.

Result: `03:00 Eastern European Time/7200000`

I bet the date is January 1st, 1970.

**Comment by melloware** [comment] 2018-01-12 15:40
Even in your example you are using `Date t = new Date(0);` which is Jan 1 1970 so it will always use Winter DST.

**Comment by chabapok** [comment] 2018-01-12 17:39
Hmmm...
If I use time range from Date(0) to Date(21 years), then my example show 03:00. If I use time range Date(22 years) and more, then my example show 02:00, and works ok.

As far as I understand, it's not a bug, it's our timezone. :) I do not remember, before 1990year (in f**ked soviet union) we used DST, or not.

Thanks for the help!

**Comment by melloware** [comment] 2018-01-12 19:55
No prob!
