### ISSUE TITLE
Sheet: filter not working in Chrome

### ISSUE THREAD

**Issue by muhdkhokhar** [primefaces-extensions/primefaces-extensions.github.com#673] opened 2019-03-23 17:20 UTC
Hi

I cannot get the filter to work in chrome and this is topping us to use this compoentn in our pap.

You can try basic example in chrome.

**Comment by jepsar** [comment] 2019-03-23 18:08
@muhdkhokhar can you please explain in detail what is not working for you? I just had a look with Chrome 73.0.3683.86 (macOS) and did not notice anything that was not working properly other than that I had to press enter and that the field lost focus after filtering.

**Comment by muhdkhokhar** [comment] 2019-03-23 19:20
On Windows OS if you use Chrome then drop down filter not workingIf you click it lose focusSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jasper de Vries <notifications@github.com> Date: 23/03/2019  18:08  (GMT+00:00) To: "primefaces-extensions/primefaces-extensions.github.com" <primefaces-extensions.github.com@noreply.github.com> Cc: Muhammad Khokhar <muhdkhokhar@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [primefaces-extensions/primefaces-extensions.github.com] Sheet filter not working in Chrome (#673) @muhdkhokhar can you please explain in detail what is not working for you? I just had a look with Chrome 73.0.3683.86 (macOS) and did not notice anything that was not working properly other than that I had to press enter and that the field lost focus after filtering.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/primefaces-extensions/primefaces-extensions.github.com","title":"primefaces-extensions/primefaces-extensions.github.com","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/primefaces-extensions/primefaces-extensions.github.com"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jepsar in #673: @muhdkhokhar can you please explain in detail what is not working for you? I just had a look with Chrome 73.0.3683.86 (macOS) and did not notice anything that was not working properly other than that I had to press enter and that the field lost focus after filtering."}],"action":{"name":"View Issue","url":"https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/673#issuecomment-475891961"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/673#issuecomment-475891961",
"url": "https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/673#issuecomment-475891961",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by melloware** [comment] 2019-03-24 12:19
This is a duplicate of the already open ticket: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/591

Closing this issue as we are already tracking it on the other one.

**Closed by melloware** 2019-03-24 12:19 UTC
