### ISSUE TITLE
Calculator: RTL or right align  digits are not displayed on main text

### ISSUE THREAD

**Issue by arunvc** [primefaces-extensions/primefaces-extensions.github.com#806] opened 2020-06-30 09:54 UTC
**Describe the bug**
RTL or right align  digits are not displayed on main textbox

![image](https://user-images.githubusercontent.com/9069988/86112209-4d935600-bae5-11ea-8bbf-089a78487f6c.png)

**Environment:**
Showcase https://www.primefaces.org/showcase-ext/sections/calculator/localization.jsf

**To Reproduce**
1. Go to https://www.primefaces.org/showcase-ext/sections/calculator/localization.jsf
2. Click on RTL
3. Type 12345

```

**Comment by melloware** [comment] 2020-06-30 11:37
Also can't reproduce:
![image](https://user-images.githubusercontent.com/4399574/86121753-95de5400-baa4-11ea-9325-5928e8baa3e3.png)

**Comment by arunvc** [comment] 2020-06-30 12:48
See the typed text is not visible in the textbox where i am typing, it appears only on the calc popup, 
Where as when its left aligned i can see my typed text on both textboxes

check this video
[sample.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4851894/sample.zip)

**Comment by melloware** [comment] 2020-06-30 12:59
This one works for me the same in RTL as LTR.  AS I am typing it only ever enters the main input text when I press the "use" button on the calculator. 

Your video is exactly what mine is doing in RTL or LTR?

**Comment by melloware** [comment] 2020-06-30 13:00
If you want it to accept your typing use "InputNumber" instead of "InputText" like in the basic example.

**Comment by melloware** [comment] 2020-06-30 14:14
OK this is fixed in 8.0.3 with commit: https://github.com/primefaces-extensions/core/commit/2ef725d15509690683b47611a340d3d2fa75c005

this makes InputNumber and InputText behave the same.  You have to use "Use" button before the value is displayed on the main input.

**Closed by melloware** 2020-06-30 14:14 UTC
Labels: bug
