### ISSUE TITLE
ERROR on MasterDetail + Dynaform + JSF-2.2.8

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [primefaces-extensions/primefaces-extensions.github.com#279] opened 2014-09-24 12:44 UTC
Binding a DialogFramework whith masterDetail component and DynaFrom component inside any masterdetailLevel... when you try to surf between masterDedailLevels, the following exception is trhown:

Grave: java.lang.StackOverflowError
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:184) 
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:172)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:239)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
 at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:973)
 at org.springframework.beans.factory.access.el.SpringBeanELResolver.getValue(SpringBeanELResolver.java:55)
 at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
 at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:72)
at org.apache.el.parser.AstValue.getValue(AstValue.java:161)
at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:185)
at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
at org.primefaces.extensions.component.base.AbstractDynamicData.getValue(AbstractDynamicData.java:110)
at org.primefaces.extensions.component.dynaform.DynaForm.invokeOnChildren(DynaForm.java:249)
at org.primefaces.extensions.component.base.AbstractDynamicData.invokeOnComponent(AbstractDynamicData.java:437)
at org.primefaces.extensions.component.dynaform.DynaForm.invokeOnChildren(DynaForm.java:262)
at org.primefaces.extensions.component.base.AbstractDynamicData.invokeOnComponent(AbstractDynamicData.java:437)
......
......

**Comment by ova2** [comment] 2015-04-06 12:09
Can you post the code here? I can not fix this issue without any sample code. You only wrote "Binding a DialogFramework whith masterDetail component and DynaFrom component inside any masterdetailLevel... when you try to surf between masterDedailLevels, the following exception is trhown:". Where is the navigation link, inside or outside of pe:dynaForm?

**Comment by ova2** [comment] 2015-04-20 19:51
Cannot reproduce with 3.1.0. Please provide more code. The stack trace is not up-to-date.

**Comment by tandraschko** [comment] 2015-08-25 21:44
I would close it Oleg - no info since 6 months.

**Closed** 2015-08-26 20:51 UTC
Labels: cannot reproduce, needs information

**Comment by sergi-mm** [comment] 2015-09-28 06:57
Hello,

I get the same error when generating multiple dynaForms inside a p:wizard component. I generate the wizard tabs dynamically from a List<Section> of tabs and the dynaForms based on a HashMap<Section,DynaModel>. The code below:
```xml
<p:wizard id="wizard">
		<c:forEach items="#{fileBean.templatesHelper.templateSections}" var="section" varStatus="loop">
			<p:tab title="#{section.title}" id="tab#{loop.index}">
				<pe:dynaForm id="dynaForm" value="#{bean.dynaFormMap.get(section.id)}" var="item">
....
</pe:dynaForm>
</p:tab>
</c:forEach>
</p:wizard>
```

I'm using Primefaces 5.2.10, Extensions 3.2.0, Mojarra 2.2.10 and Tomcat 7.0.57. And the error below:
```java
sep 28, 2015 8:38:54 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler handle
GRAVE: null
java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:1016)
	at java.util.Collections$SetFromMap.contains(Collections.java:3901)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.isSingletonCurrentlyInCreation(DefaultSingletonBeanRegistry.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:185)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getSingleton(DefaultListableBeanFactory.java)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:172)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:239)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:973)
	at org.springframework.beans.factory.access.el.SpringBeanELResolver.getValue(SpringBeanELResolver.java:55)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:71)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:160)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
	at com.sun.faces.facelets.tag.jstl.core.IndexedValueExpression.getValue(IndexedValueExpression.java:92)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:67)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:160)
	at org.apache.el.parser.AstMethodParameters.getParameters(AstMethodParameters.java:33)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:172)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
	at org.primefaces.extensions.component.base.AbstractDynamicData.getValue(AbstractDynamicData.java:110)
	at org.primefaces.extensions.component.dynaform.DynaForm.invokeOnChildren(DynaForm.java:243)
	at org.primefaces.extensions.component.base.AbstractDynamicData.invokeOnComponent(AbstractDynamicData.java:437)
	at org.primefaces.extensions.component.dynaform.DynaForm.invokeOnChildren(DynaForm.java:256)
	at org.primefaces.extensions.component.base.AbstractDynamicData.invokeOnComponent(AbstractDynamicData.java:437)
```

**Comment by bilelovitch** [comment] 2016-08-04 10:46
Hi,
i get the same error when i try to submit a dynamic form with a required form unfilled.
