### ISSUE TITLE
Sheet : cannot insert row on empty data

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#606] opened 2018-08-16 14:29 UTC
PE 6.2.8
Cannot insert a row on empty data 
`TypeError: d[Math.max(...)] is undefined[En savoir plus] sheet.source.js:51712:48
`
How is it possible to insert the fisrt line on an empty data ?
Is it possible to set a default value 0 if there is no data (no lenght) or something like this ?

**Comment by melloware** [comment] 2018-08-16 14:38
So is your scenario the sheet is empty and then you right click on the context menu and choose "Insert Row"?  Is that how you got this error?

**Comment by awenger63** [comment] 2018-08-16 14:43
Yes right !

**Comment by melloware** [comment] 2018-08-16 14:49
OK I will investigate.

**Comment by melloware** [comment] 2018-08-16 15:37
Fixed with commit: https://github.com/primefaces-extensions/core/commit/c70bf78f2026a6dc32e1a5df646cd87453c4f266

**Comment by awenger63** [comment] 2018-08-16 16:01
Thanks, I will try it on next version

**Comment by awenger63** [comment] 2018-10-19 09:13
Hi @melloware 
I applied new version 6.2.9, code is update like your commit, but issue alway exist. See console log 
` [Afficher/Masquer les détails du message.] TypeError: c[Math.max(...)] is undefined[En savoir plus] sheet.source.js:56984:48
callback
sheet.source.js:56984:48
value/<
sheet.source.js:56048:15
h
sheet.source.js:1726:8
value
sheet.source.js:56047:7
value
sheet.source.js:55838:6
f/<
sheet.source.js:55711:17
runLocalHooks/<
sheet.source.js:12144:15
h
sheet.source.js:1726:8
runLocalHooks
sheet.source.js:12143:7
value
sheet.source.js:57473:6
value
sheet.source.js:57955:8
value/<
sheet.source.js:57186:15
g
sheet.source.js:2161:8
`

**Comment by melloware** [comment] 2018-10-19 10:46
I can't reproduce.  Can you give me exact steps on how you are getting this error?

**Comment by melloware** [comment] 2018-10-19 10:52
OK I found it.  The error is in the example code not in the component. When you have a table with no rows here is the JavaScript for the menu to show the "Insert Rows Above".

```javascript
"row_above": {
               disabled: function () {
                 // if first row, disable this option
                 return $hot.getSelected()[0] === 0;
               }
             },
```
However $hot.getSelected()[0]  is not valid. So you need to add a check for length before doing that check.

Something like...
```javascript
"row_above": {
               disabled: function () {
                 // if first row, disable this option
                 var selected = $hot.getSelected();
                 if (selected && selected.length > 0) {
                     return $hot.getSelected()[0] === 0;
                 }
                 return false;
               }
             },
```
Note: I did not test this just suggesting how to fix it.

**Closed by melloware** 2018-10-19 10:52 UTC
Labels: bug

**Comment by awenger63** [comment] 2018-10-19 17:59
I understand, but I always want insert row, so here his my code 
`"row_above": {disabled: function () {return false;}`

**Comment by melloware** [comment] 2018-10-19 18:02
Perfect!

**Comment by melloware** [comment] 2018-10-19 20:31
Looks like a bug in HandsonTable it won't let you add rows to an empty sheet.   Looks like the must have broken this in the latest version.

**Comment by awenger63** [comment] 2018-10-20 06:52
I'll take a look and tell you back

**Comment by awenger63** [comment] 2018-10-20 15:38
@melloware I found where is it possible to change something to insert row on empty sheet. I think it's not an handsontable bug, because I test this command on empty datatable and it seem's working
`this.alter('insert_row', 0, 1, 'ContextMenu.rowAbove');`

So perhaps we can change theses lines on sheet.js in function rowAboveItem()

`
callback: function callback(key, normalizedSelection) {
      var latestSelection = normalizedSelection[Math.max(normalizedSelection.length - 1, 0)];
 if (typeOf latestSelection === 'undefined') {
      this.alter('insert_row', 0, 1, 'ContextMenu.rowAbove');
} else {
      this.alter('insert_row', latestSelection.start.row, 1, 'ContextMenu.rowAbove');
}
    },
`
What do you mean ?

**Comment by melloware** [comment] 2018-10-21 15:34
but that rowAboveItem() call is from HandsonTable right?  So I would be making changes to the core Handsontable code, we should report the issue to Handsontable if that is where the code change needs to happen?

**Comment by awenger63** [comment] 2018-10-21 20:47
You totally right, I'm confuse, I do the mistake because source is in https://github.com/primefaces-extensions/core/blob/master/src/sourcemap/6.2.9/sheet.source.js and I'm a little in hurry.
Thanks for your help, Sorry for that. ( look handsontable issue 5536 ;-) )

**Comment by melloware** [comment] 2018-10-22 11:22
Added reference: https://github.com/handsontable/handsontable/issues/5536
