### ISSUE TITLE
showcase error on example for invisible timer

### ISSUE THREAD

**Issue by oliver303** [primefaces-extensions/primefaces-extensions.github.com#490] opened 2017-09-21 10:27 UTC
The link https://www.primefaces.org/showcase-ext/sections/timer/invisible.jsf gives an error. See output.

**Comment by melloware** [comment] 2017-09-21 11:38
Thanks I had noticed this myself already and its fixed in 6.2 Showcase.  The problem is <pe:knob> was moved into PF so its now <p:knob>

If you need to see the example working just checkout our showcase and run mvn clean jetty:run from here:  https://github.com/primefaces-extensions/showcase

**Closed** 2017-09-21 11:38 UTC
Labels: fixed

**Comment by oliver303** [comment] 2017-09-23 11:04
Thanks! That works.
