### ISSUE TITLE
Calculator: digits after comma is lost in calculator pop up

### ISSUE THREAD

**Issue by arunvc** [primefaces-extensions/primefaces-extensions.github.com#805] opened 2020-06-30 08:07 UTC
**Describe the bug**

The digits after the the comma is lost in calculator pop up

![image](https://user-images.githubusercontent.com/9069988/86100700-d22aa800-bad6-11ea-8dde-3d593e604586.png)

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.8 or MyFaces 2.3.6_
 - Affected browsers: _e.g. Firefox, Ubuntu, ALL_

**To Reproduce**
1. Go to https://www.primefaces.org/showcase-ext/sections/calculator/basicUsage.jsf
2. Enter a number 5 digit number eg 12345 on Calculator with button on a p:inputNumber
3. Click outside and click the calc button again.
4. Number in calculator becomes 12

**Expected behavior**
12345 should be displayed on calculator window

```


```

**Comment by melloware** [comment] 2020-06-30 11:36
I can't reproduce:
![image](https://user-images.githubusercontent.com/4399574/86121663-67607900-baa4-11ea-89ed-7b172c5897b7.png)

**Comment by arunvc** [comment] 2020-06-30 12:52
After entering an amount click the calc icon the digits after coma is lost.

Check this out
[comma.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4851914/comma.zip)

**Comment by melloware** [comment] 2020-06-30 12:57
OK that video helps me see it.

**Comment by melloware** [comment] 2020-06-30 14:13
OK this is fixed in 8.0.3 with commit: https://github.com/primefaces-extensions/core/commit/2ef725d15509690683b47611a340d3d2fa75c005

**Closed** 2020-06-30 14:13 UTC
Labels: bug
