### ISSUE TITLE
LetterAvatar: unable to use inside of timeline

### ISSUE THREAD

**Issue by mores** [primefaces-extensions/primefaces-extensions.github.com#727] opened 2019-09-24 14:56 UTC
pe:gravatar works just fine inside of timeline.  Working example: https://github.com/mores/primefaces-test/tree/timeline001-avatar

Tried to replace
<pe:gravatar value="#{timelineEventObject.name}" size="57" notFound="monsterid" />
with
<pe:letterAvatar value="#{timelineEventObject.name}" height="57" width="57" />

But no image is rendered.

**Comment by melloware** [comment] 2019-09-24 15:16
Thanks for the reproducer!

**Comment by melloware** [comment] 2019-09-24 15:39
OK I think it might be a Timeline issue.  The only reason gravtar works is because Gravatar doesn't use any Javascript it only renders an `<img>` tag.  But LetterAvatar needs to execute JS.  I don't think any PrimeFaces component works in the Timeline.

Try replacing with Colorpicker...
```xml
<p:colorPicker value="#{timelineEventObject.name}" mode="inline" />
```

YOu will see in the Timeline it generates the widget script.
```javascript
$(function(){PrimeFaces.cw("ColorPicker","widget_j_idt6_j_idt8",{id:"j_idt6:j_idt8",mode:"inline",color:"DataBase Id: 2"});});
```

But its never being called because the Timeline is just rendering it as text.

**Comment by melloware** [comment] 2019-09-25 11:11
I am going to close this since it appears not to be LetterAvatar related but Timeline related.

**Closed by melloware** 2019-09-25 11:11 UTC
Labels: bug
