### ISSUE TITLE
Showcase does not work on small screen devices

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#738] opened 2019-10-12 09:00 UTC
I wanted to test the TimePicker on my phone and was unable to navigate to it

**Comment by melloware** [comment] 2019-10-14 11:44
Relates to https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/444

**Comment by melloware** [comment] 2019-10-21 18:17
Closing as duplicate of #444

**Closed by melloware** 2019-10-21 18:17 UTC
Labels: enhancement
