### ISSUE TITLE
Sheet: Cannot scroll in sheet (Firefox Only)

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions.github.com#612] opened 2018-09-06 10:38 UTC
scrolling does not seem to work in a sheet

Reproduce: https://web2.fa.knaw.nl/oat/ (ask me for login and steps via mail or message)

**Comment by melloware** [comment] 2018-09-06 14:57
Can you past your pe:sheet XHTML snippet so I can see it?

**Comment by eduarddrenth** [comment] 2018-09-06 21:27
```
    <p:panel header="percelen #{perceelSheetController.oatScan.code}" class="percelensheet" id="perceelsheetpanel" style="width: 99%" widgetVar="perceelsheetpanel">
        <h:form onsubmit="return false;" id="percelensheetForm"><p:commandButton styleClass="noEnter" value="" onclick="return false;"/>
            <p:commandButton icon="ui-icon-plus" actionListener="#{perceelSheetController.prepareCreate()}" id="nieuw"
                             update="sheet" styleClass="nieuw" title="voeg nieuwe toe" oncomplete="scrollDown();"
                             disabled="#{perceelSheetController.oatScan == null or perceelSheetController.percelen.size() > 49}"/>
            <pe:sheet id="sheet" widgetVar="sheetWidget" value="#{perceelSheetController.percelen}" var="row" rowStyleClass="sheetrow"
                      rowKey="#{perceelSheetController.getRowKey(row.id)}" showRowHeaders="true"
            resizableCols="true" resizableRows="true" filteredValue="#{perceelSheetController.filtering.filtered}"  readOnly="false">  

                <p:ajax event="change" listener="#{perceelSheetController.cellChangeEvent}"
                        update="percelenForm:percelentable"/>
    
                <pe:sheetcolumn headerText="nr" value="#{row.perceelnr}" colType="numeric" required="true" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="nrtvg" value="#{row.perceelnrtvg}"/>
                <pe:sheetcolumn headerText="art" value="#{row.artikel}" required="true" colWidth="220"
                                colType="dropdown" selectItems="#{perceelSheetController.availableArtikelen}"/>
                <pe:sheetcolumn headerText="volgnr" value="#{row.volgnr}" colType="numeric" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="volgnrtvg" value="#{row.volgnrtvg}"/>
                <pe:sheetcolumn headerText="opvolgnrs" value="#{row.opvolgnrs}"/>
                <pe:sheetcolumn headerText="pl. naam" value="#{row.plaatselijke_benaming}"  colType="text"/>
                <pe:sheetcolumn headerText="gebruik" value="#{row.grondGebruik}"  colWidth="120"
                                colType="autocomplete" selectItems="#{perceelSheetController.grondGebruik()}" required="true" autoCompleteAllowInvalid="true"/>
                <pe:sheetcolumn headerText="opp" value="#{row.oppervlak}"  colType="numeric" required="true" numericPattern="#,###" />
                <pe:sheetcolumn headerText="dijklasten" value="#{row.klasse_dijklasten}" colType="numeric" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="aftrek" value="#{row.aftrek}" colType="numeric" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="bel. inkomen" value="#{row.belastbaar_inkomen}" colType="numeric" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="bel. inkomen geb." value="#{row.belastbaar_inkomen_gebouwd}" colType="numeric" numericPattern="#,###"/>
                <pe:sheetcolumn headerText="geschrapt" value="#{row.geschrapt}" colType="text" required="true"/>
                <pe:sheetcolumn headerText="sat" value="#{row.sat}" colType="text"/>
                <pe:sheetcolumn headerText="toponiem" value="#{row.toponiem}" colType="text"/>
            </pe:sheet>
            <p:commandButton icon="ui-icon-plus" title="nieuwe toevoegen" styleClass="extranieuw" onclick="clickNew(event); return false;"/>
        </h:form>
    </p:panel>
```

**Comment by melloware** [comment] 2018-09-08 13:40
I don't see anything out of the ordinary here compared to what I am doing in the Showcase.  So there must be something else your project includes that is causing this issue we just need to figure out what that is!

**Comment by melloware** [comment] 2018-09-08 13:41
Or you can e-mail me a login to your site above to info <at> melloware <dot> com

**Comment by melloware** [comment] 2018-09-09 14:43
Is this one also Firefox specific?

**Comment by eduarddrenth** [comment] 2018-09-09 15:36
yes

**Comment by melloware** [comment] 2018-09-11 11:51
Found these related issues:
https://github.com/handsontable/handsontable/issues/5212
https://github.com/handsontable/handsontable/issues/4971
https://github.com/handsontable/handsontable/issues/4521

**Comment by eduarddrenth** [comment] 2018-09-11 13:42
giving the sheet a height, together with the fix from https://github.com/handsontable/handsontable/issues/7 solves the scrolling issue as well

**Comment by melloware** [comment] 2018-09-11 13:54
Woo hoo!  So you had no height on the sheet?

**Comment by eduarddrenth** [comment] 2018-09-11 15:42
no, at first I had, but I would like the sheet to work without it, looks very nice at first glance, but dropdowns don't layout very well when height isn't set.
So I decided to set a height, this causes a scrollbar to appear as needed in the sheet, whcih works more intuitive, but....
When the containing page as well has a scrollbar and the mouse is above the sheet, the page doesn't scroll when you come at the end of the scroll region of the sheet.

**Comment by melloware** [comment] 2018-09-11 15:58
You mean with the mousewheel right?

**Comment by eduarddrenth** [comment] 2018-09-11 18:44
with the weal yes...

I'll read it, have already seen some warnings on usage of height/width on sheet

**Comment by melloware** [comment] 2018-09-12 11:44
I think this one is your Mousewheel issue: https://github.com/handsontable/handsontable/issues/4521

**Comment by melloware** [comment] 2018-09-26 11:28
I am going to close this issue for now as we have rooted the cause to the underlying HandsonTable.

**Closed by melloware** 2018-09-26 11:28 UTC
Labels: bug

**Comment by eduarddrenth** [comment] 2018-09-26 11:38
fine
